# Generated by Django 3.2.8 on 2022-03-24 04:05

import django.core.validators
from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', validators=[posts.validators.fileSize, django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
