# Generated by Django 3.2.8 on 2022-03-11 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(default='background.png', upload_to='backgrounds')),
                ('bio', models.TextField(blank=True, default='no bio...', max_length=255)),
                ('address', models.TextField(blank=True, max_length=255)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usertype', models.TextField(blank=True, default='Veterinarian')),
                ('avatar', models.ImageField(default='vet_avatar.png', upload_to='avatars')),
                ('following', models.ManyToManyField(blank=True, related_name='vet_following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(default='background.png', upload_to='backgrounds')),
                ('bio', models.TextField(blank=True, default='no bio...', max_length=255)),
                ('address', models.TextField(blank=True, max_length=255)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(default='store_avatar.png', upload_to='avatars')),
                ('usertype', models.TextField(blank=True, default='Store')),
                ('store_type', models.CharField(choices=[('PETSTORE', 'Pet Store'), ('PRODUCTSTORE', 'Pet Product Store')], max_length=50)),
                ('following', models.ManyToManyField(blank=True, related_name='store_following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet_Lover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(default='background.png', upload_to='backgrounds')),
                ('bio', models.TextField(blank=True, default='no bio...', max_length=255)),
                ('address', models.TextField(blank=True, max_length=255)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usertype', models.TextField(blank=True, default='Pet Lover')),
                ('avatar', models.ImageField(default='avatar.png', upload_to='avatars')),
                ('following', models.ManyToManyField(blank=True, related_name='petLover_following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='petLover', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(default='background.png', upload_to='backgrounds')),
                ('bio', models.TextField(blank=True, default='no bio...', max_length=255)),
                ('address', models.TextField(blank=True, max_length=255)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(default='pet_avatar.png', upload_to='avatars')),
                ('usertype', models.TextField(blank=True, default='Pet')),
                ('pet_type', models.CharField(blank=True, choices=[('FISH', 'Fish'), ('REPTILE', 'Reptile'), ('BIRD', 'Bird'), ('AMPHIBIAN', 'Amphibian'), ('MAMMAL', 'Mammal'), ('OTHER', 'Other')], max_length=50)),
                ('fish_type', models.CharField(blank=True, choices=[('BETTA', 'Betta'), ('GOLDFISH', 'Goldfish'), ('ANGELFISH', 'Angelfish'), ('GUPPIES', 'Guppies'), ('NEONTETRAS', 'Neon Tetras'), ('ZEBRADANIOS', 'Zebra Danios'), ('MOLLIES', 'Mollies'), ('CATFISH', 'Catfish'), ('CHERRYBARB', 'Cherry Barb'), ('PLATY', ' Platy'), ('SWORDTAIL', ' Swordtail'), ('OTHER', 'Other')], max_length=50)),
                ('reptile_type', models.CharField(blank=True, choices=[('BEARDEDDRAGON', 'Bearded Dragon'), ('GECKOS', 'Leopard Gecko'), ('TURTLES', 'Turtle'), ('TORTOISE', 'Tortoise'), ('CORNSNAKES', 'Corn Snake'), ('ZEBRADANIOS', 'Ball Python'), ('CRESTEDGECKO', 'Crested Gecko'), ('SKINK', 'Blue-Tongued Skink'), ('GREENIGUANA', 'Green Iguana'), ('ANOLE', ' Anole'), ('SNAKE', 'Snake'), ('WATERDRAGON', 'Water Dragon'), ('OTHER', 'Other')], max_length=50)),
                ('bird_type', models.CharField(blank=True, choices=[('PARROT', 'Parrot'), ('COCKTIEL', 'Cockatiel'), ('FINCH', 'Finch'), ('COCKATOO', 'Cockatoo'), ('CANARY', 'Canary'), ('LOVEBIRD', 'Lovebird'), ('PARAKEET', 'Parakeet'), ('DOVE', 'Dove'), ('CONURES', 'Conures'), ('MACAW', 'Macaw'), ('OTHER', 'Other')], max_length=50)),
                ('amphibian_type', models.CharField(blank=True, choices=[('TREEFROG', 'Tree Frog'), ('SALMANDER', 'Salamander'), ('AXOLOTL', 'Axolotl'), ('PACEMANFROG', 'Pacman Frog'), ('OFBT', 'Oriental Fire-Bellied Toad'), ('EASTERNNEWT', 'Eastern Newt'), ('OTHER', 'Other')], max_length=50)),
                ('mammal_type', models.CharField(blank=True, choices=[('GERBIL', 'Gerbil'), ('DOG', 'Dog'), ('CAT', 'Cat'), ('HAMSTER', 'Hamster'), ('RABBIT', 'Rabbit'), ('RAT', 'Rat'), ('PIG', 'Guinea Pig'), ('FERRET', 'Ferret'), ('HEDGEHOG', 'Hedgehog'), ('FFOXES', ' Fennec Foxes'), ('OTHER', 'Other')], max_length=50)),
                ('breed', models.TextField(blank=True, max_length=50)),
                ('following', models.ManyToManyField(blank=True, related_name='pet_following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
