# Generated by Django 3.2.8 on 2022-02-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='amphibian_type',
            field=models.CharField(blank=True, choices=[('TREEFROG', 'Tree Frog'), ('SALMANDER', 'Salamander'), ('AXOLOTL', 'Axolotl'), ('PACEMANFROG', 'Pacman Frog'), ('OFBT', 'Oriental Fire-Bellied Toad'), ('EASTERNNEWT', 'Eastern Newt'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='bird_type',
            field=models.CharField(blank=True, choices=[('PARROT', 'Parrot'), ('COCKTIEL', 'Cockatiel'), ('FINCH', 'Finch'), ('COCKATOO', 'Cockatoo'), ('CANARY', 'Canary'), ('LOVEBIRD', 'Lovebird'), ('PARAKEET', 'Parakeet'), ('DOVE', 'Dove'), ('CONURES', 'Conures'), ('MACAW', 'Macaw'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='fish_type',
            field=models.CharField(blank=True, choices=[('BETTA', 'Betta'), ('GOLDFISH', 'Goldfish'), ('ANGELFISH', 'Angelfish'), ('GUPPIES', 'Guppies'), ('NEONTETRAS', 'Neon Tetras'), ('ZEBRADANIOS', 'Zebra Danios'), ('MOLLIES', 'Mollies'), ('CATFISH', 'Catfish'), ('CHERRYBARB', 'Cherry Barb'), ('PLATY', ' Platy'), ('SWORDTAIL', ' Swordtail'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='mammal_type',
            field=models.CharField(blank=True, choices=[('GERBIL', 'Gerbil'), ('DOG', 'Dog'), ('CAT', 'Cat'), ('HAMSTER', 'Hamster'), ('RABBIT', 'Rabbit'), ('RAT', 'Rat'), ('PIG', 'Guinea Pig'), ('FERRET', 'Ferret'), ('HEDGEHOG', 'Hedgehog'), ('FFOXES', ' Fennec Foxes'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='reptile_type',
            field=models.CharField(blank=True, choices=[('BEARDEDDRAGON', 'Bearded Dragon'), ('GECKOS', 'Leopard Gecko'), ('TURTLES', 'Turtle'), ('TORTOISE', 'Tortoise'), ('CORNSNAKES', 'Corn Snake'), ('ZEBRADANIOS', 'Ball Python'), ('CRESTEDGECKO', 'Crested Gecko'), ('SKINK', 'Blue-Tongued Skink'), ('GREENIGUANA', 'Green Iguana'), ('ANOLE', ' Anole'), ('SNAKE', 'Snake'), ('WATERDRAGON', 'Water Dragon'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(blank=True, choices=[('FISH', 'Fish'), ('REPTILE', 'Reptile'), ('BIRD', 'Bird'), ('AMPHIBIAN', 'Amphibian'), ('MAMMAL', 'Mammal'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
