# Generated by Django 3.2.8 on 2022-02-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlover_profile',
            name='bio',
            field=models.TextField(blank=True, default='no bio...'),
        ),
        migrations.AlterField(
            model_name='petlover_profile',
            name='type',
            field=models.PositiveSmallIntegerField(default='PETLOVER'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='bio',
            field=models.TextField(blank=True, default='no bio...'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_type',
            field=models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('FISH', 'Fish'), ('HAMSTER', 'Hamster'), ('RABBIT', 'Rabbit'), ('MOUSE', 'Mouse'), ('TURTLE', 'Turtle'), ('REPTILE', 'Reptile'), ('BIRD', 'Bird'), ('AMPHIBIAN', 'Amphibian'), ('MAMMAL', 'Mammal'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='type',
            field=models.PositiveSmallIntegerField(default='PET'),
        ),
        migrations.AlterField(
            model_name='store_profile',
            name='bio',
            field=models.TextField(blank=True, default='no bio...'),
        ),
        migrations.AlterField(
            model_name='store_profile',
            name='type',
            field=models.PositiveSmallIntegerField(default='STORE'),
        ),
        migrations.AlterField(
            model_name='vetprofile',
            name='bio',
            field=models.TextField(blank=True, default='no bio...'),
        ),
        migrations.AlterField(
            model_name='vetprofile',
            name='type',
            field=models.PositiveSmallIntegerField(default='VET'),
        ),
    ]
