# Generated by Django 4.0.3 on 2022-09-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_store_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
