# Generated by Django 3.2.8 on 2022-04-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='pet_avatar.png', upload_to='avatars'),
        ),
    ]
