# Generated by Django 3.2.8 on 2022-04-01 12:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_profilepic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pet_lover',
            managers=[
                ('profiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('profiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='store',
            managers=[
                ('profiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='veterinarian',
            managers=[
                ('profiles', django.db.models.manager.Manager()),
            ],
        ),
    ]
