# Generated by Django 3.2.8 on 2022-04-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220401_1825'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pet_lover',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='store',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='veterinarian',
            managers=[
            ],
        ),
    ]
