# Generated by Django 3.2.8 on 2022-02-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('PET', 'Pet'), ('VET', 'Veterinarian'), ('STORE', 'Store'), ('PET_LOVER', 'Pet lover')], default='PET_LOVER', max_length=50),
        ),
    ]
